/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PracticaPaint;

import sm.msm.graficos.Lienzo2DImagen;

/**
 *
 * @author Miguel
 */
public class VentanaDibujo extends javax.swing.JInternalFrame {
    
    VentanaPrincipal MiVentanaPrincipal;

    /**
     * Creates new form VentanaInterna
     * 
     * @param v Ventana dentro de la que está.
     */
    public VentanaDibujo(VentanaPrincipal v) {
        MiVentanaPrincipal = v;   
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Lienzo = new sm.msm.graficos.Lienzo2DImagen();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        Lienzo.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                LienzoMouseMoved(evt);
            }
        });

        javax.swing.GroupLayout LienzoLayout = new javax.swing.GroupLayout(Lienzo);
        Lienzo.setLayout(LienzoLayout);
        LienzoLayout.setHorizontalGroup(
            LienzoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 392, Short.MAX_VALUE)
        );
        LienzoLayout.setVerticalGroup(
            LienzoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 276, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(Lienzo);

        getContentPane().add(jScrollPane1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated
        //Para cuando cambiamos de una ventana a otro
        MiVentanaPrincipal.modificaciones();  
    }//GEN-LAST:event_formInternalFrameActivated

    private void LienzoMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LienzoMouseMoved
        MiVentanaPrincipal.cambiarCoordenadas(Lienzo.getCoordenadas());
    }//GEN-LAST:event_LienzoMouseMoved

    public Lienzo2DImagen getLienzo(){
        return Lienzo;
    }
    
    public void setLienzo(Lienzo2DImagen Lienzo){
        this.Lienzo = Lienzo;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private sm.msm.graficos.Lienzo2DImagen Lienzo;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
