/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package practica7;
import sm.msm.graficos.Lienzo2D;
import sm.msm.iu.Lienzo2DImagen;
/**
 *
 * @author Miguel
 */
public class VentanaInterna extends javax.swing.JInternalFrame {
    private VentanaPrincipal Windows ;
    /**
     * Creates new form VentanaInterna
     */
    
    public VentanaInterna(){
        initComponents();
        this.Windows = new VentanaPrincipal();
    }
    
    public VentanaInterna(VentanaPrincipal vPrincipal) {
        initComponents();
        this.Windows = vPrincipal;
    }

    public Lienzo2DImagen getLienzo(){
        return lienzo2dimagen;
    }
    
    public void setLienzo(Lienzo2DImagen li){
        this.lienzo2dimagen = li;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        lienzo2dimagen = new sm.msm.iu.Lienzo2DImagen();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        javax.swing.GroupLayout lienzo2dimagenLayout = new javax.swing.GroupLayout(lienzo2dimagen);
        lienzo2dimagen.setLayout(lienzo2dimagenLayout);
        lienzo2dimagenLayout.setHorizontalGroup(
            lienzo2dimagenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 382, Short.MAX_VALUE)
        );
        lienzo2dimagenLayout.setVerticalGroup(
            lienzo2dimagenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 262, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(lienzo2dimagen);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated
        // TODO add your handling code here:
        Windows.RecuperarDatos();
    }//GEN-LAST:event_formInternalFrameActivated


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private sm.msm.iu.Lienzo2DImagen lienzo2dimagen;
    // End of variables declaration//GEN-END:variables
}
