/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package practica4;

import java.awt.Color;
import java.io.File;
import javax.swing.JFileChooser;

/**
 *
 * @author Migue
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {        
        initComponents();
        this.BotonLapiz.setSelected(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BarraColores = new javax.swing.ButtonGroup();
        BotonesHerramientas = new javax.swing.ButtonGroup();
        BarraHerramientas = new javax.swing.JToolBar();
        BotonLapiz = new javax.swing.JToggleButton();
        BotonLinea = new javax.swing.JToggleButton();
        BotonRectangulo = new javax.swing.JToggleButton();
        BotonOvalo = new javax.swing.JToggleButton();
        BarraEstado = new javax.swing.JLabel();
        VistaGrafica = new javax.swing.JPanel();
        BarraPaleta = new javax.swing.JPanel();
        PaletaColores = new javax.swing.JPanel();
        BotonNegro = new javax.swing.JToggleButton();
        BotonRojo = new javax.swing.JToggleButton();
        BotonAzul = new javax.swing.JToggleButton();
        BotonBlanco = new javax.swing.JToggleButton();
        BotonAmarillo = new javax.swing.JToggleButton();
        BotonVerde = new javax.swing.JToggleButton();
        CheckBoxRelleno = new javax.swing.JCheckBox();
        Lienzo = new practica4.Lienzo();
        BarraMenu = new javax.swing.JMenuBar();
        BotonArchivo = new javax.swing.JMenu();
        BotonNuevo = new javax.swing.JMenuItem();
        BotonAbrir = new javax.swing.JMenuItem();
        BotonGuardar = new javax.swing.JMenuItem();
        BotonEdicion = new javax.swing.JMenu();
        CheckBoxBarraEstado = new javax.swing.JCheckBoxMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BarraHerramientas.setRollover(true);

        BotonesHerramientas.add(BotonLapiz);
        BotonLapiz.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Lapiz.gif"))); // NOI18N
        BotonLapiz.setFocusable(false);
        BotonLapiz.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BotonLapiz.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BotonLapiz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonLapizActionPerformed(evt);
            }
        });
        BarraHerramientas.add(BotonLapiz);

        BotonesHerramientas.add(BotonLinea);
        BotonLinea.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Linea.gif"))); // NOI18N
        BotonLinea.setFocusable(false);
        BotonLinea.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BotonLinea.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BotonLinea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonLineaActionPerformed(evt);
            }
        });
        BarraHerramientas.add(BotonLinea);

        BotonesHerramientas.add(BotonRectangulo);
        BotonRectangulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Rectangulo.gif"))); // NOI18N
        BotonRectangulo.setFocusable(false);
        BotonRectangulo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BotonRectangulo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BotonRectangulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonRectanguloActionPerformed(evt);
            }
        });
        BarraHerramientas.add(BotonRectangulo);

        BotonesHerramientas.add(BotonOvalo);
        BotonOvalo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Ovalo.gif"))); // NOI18N
        BotonOvalo.setFocusable(false);
        BotonOvalo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BotonOvalo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BotonOvalo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonOvaloActionPerformed(evt);
            }
        });
        BarraHerramientas.add(BotonOvalo);

        getContentPane().add(BarraHerramientas, java.awt.BorderLayout.PAGE_START);

        BarraEstado.setText("Barra de Estado");
        getContentPane().add(BarraEstado, java.awt.BorderLayout.PAGE_END);

        VistaGrafica.setLayout(new java.awt.BorderLayout());

        BarraPaleta.setLayout(new java.awt.BorderLayout());

        PaletaColores.setLayout(new java.awt.GridLayout(2, 3));

        BotonNegro.setBackground(new java.awt.Color(0, 0, 0));
        BarraColores.add(BotonNegro);
        BotonNegro.setPreferredSize(new java.awt.Dimension(25, 25));
        BotonNegro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonNegroActionPerformed(evt);
            }
        });
        PaletaColores.add(BotonNegro);

        BotonRojo.setBackground(new java.awt.Color(255, 0, 0));
        BarraColores.add(BotonRojo);
        BotonRojo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonRojoActionPerformed(evt);
            }
        });
        PaletaColores.add(BotonRojo);

        BotonAzul.setBackground(new java.awt.Color(0, 0, 204));
        BarraColores.add(BotonAzul);
        BotonAzul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAzulActionPerformed(evt);
            }
        });
        PaletaColores.add(BotonAzul);

        BotonBlanco.setBackground(new java.awt.Color(255, 255, 255));
        BarraColores.add(BotonBlanco);
        BotonBlanco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonBlancoActionPerformed(evt);
            }
        });
        PaletaColores.add(BotonBlanco);

        BotonAmarillo.setBackground(new java.awt.Color(255, 255, 0));
        BarraColores.add(BotonAmarillo);
        BotonAmarillo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAmarilloActionPerformed(evt);
            }
        });
        PaletaColores.add(BotonAmarillo);

        BotonVerde.setBackground(new java.awt.Color(0, 153, 0));
        BarraColores.add(BotonVerde);
        BotonVerde.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonVerdeActionPerformed(evt);
            }
        });
        PaletaColores.add(BotonVerde);

        BarraPaleta.add(PaletaColores, java.awt.BorderLayout.LINE_START);

        CheckBoxRelleno.setText("Relleno");
        CheckBoxRelleno.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                CheckBoxRellenoItemStateChanged(evt);
            }
        });
        CheckBoxRelleno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckBoxRellenoActionPerformed(evt);
            }
        });
        BarraPaleta.add(CheckBoxRelleno, java.awt.BorderLayout.LINE_END);

        VistaGrafica.add(BarraPaleta, java.awt.BorderLayout.PAGE_END);

        Lienzo.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout LienzoLayout = new javax.swing.GroupLayout(Lienzo);
        Lienzo.setLayout(LienzoLayout);
        LienzoLayout.setHorizontalGroup(
            LienzoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 682, Short.MAX_VALUE)
        );
        LienzoLayout.setVerticalGroup(
            LienzoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 311, Short.MAX_VALUE)
        );

        VistaGrafica.add(Lienzo, java.awt.BorderLayout.CENTER);

        getContentPane().add(VistaGrafica, java.awt.BorderLayout.CENTER);

        BotonArchivo.setText("Archivo");

        BotonNuevo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.ALT_MASK));
        BotonNuevo.setText("Nuevo");
        BotonNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonNuevoActionPerformed(evt);
            }
        });
        BotonArchivo.add(BotonNuevo);

        BotonAbrir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.ALT_MASK));
        BotonAbrir.setText("Abrir");
        BotonAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAbrirActionPerformed(evt);
            }
        });
        BotonArchivo.add(BotonAbrir);

        BotonGuardar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.ALT_MASK));
        BotonGuardar.setText("Guardar");
        BotonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonGuardarActionPerformed(evt);
            }
        });
        BotonArchivo.add(BotonGuardar);

        BarraMenu.add(BotonArchivo);

        BotonEdicion.setText("Edicion");

        CheckBoxBarraEstado.setSelected(true);
        CheckBoxBarraEstado.setText("Ver Barra de Estado");
        CheckBoxBarraEstado.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                CheckBoxBarraEstadoStateChanged(evt);
            }
        });
        CheckBoxBarraEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckBoxBarraEstadoActionPerformed(evt);
            }
        });
        BotonEdicion.add(CheckBoxBarraEstado);

        BarraMenu.add(BotonEdicion);

        setJMenuBar(BarraMenu);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /*El boton nuevo llama a limpiaVentana para poner a null los puntos y llama a repain*/
    private void BotonNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonNuevoActionPerformed
        this.Lienzo.LimpiarVentana();
        this.Lienzo.repaint();
    }//GEN-LAST:event_BotonNuevoActionPerformed

    private void BotonAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAbrirActionPerformed
        // TODO add your handling code here:
         JFileChooser dlg = new JFileChooser();
        int resp = dlg.showOpenDialog(this);
        if( resp == JFileChooser.APPROVE_OPTION) {
            File f = dlg.getSelectedFile();
        }
    }//GEN-LAST:event_BotonAbrirActionPerformed

    private void BotonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonGuardarActionPerformed
        // TODO add your handling code here:
         JFileChooser dlg = new JFileChooser();
        int resp = dlg.showSaveDialog(this);
        if( resp == JFileChooser.APPROVE_OPTION) {
            File f = dlg.getSelectedFile();
        }
    }//GEN-LAST:event_BotonGuardarActionPerformed

    private void CheckBoxBarraEstadoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_CheckBoxBarraEstadoStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_CheckBoxBarraEstadoStateChanged

    private void CheckBoxBarraEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckBoxBarraEstadoActionPerformed
        // TODO add your handling code here:
        this.BarraEstado.setVisible(this.CheckBoxBarraEstado.isSelected());
        
    }//GEN-LAST:event_CheckBoxBarraEstadoActionPerformed
    /*Cuando pulsamos el boton de negro, en barra de estado pone Negro y manda a lienzo el color negro */
    private void BotonNegroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonNegroActionPerformed
        // TODO add your handling code here:
        this.BarraEstado.setText("Negro");
        this.Lienzo.setColor(Color.black);
       
    }//GEN-LAST:event_BotonNegroActionPerformed

    private void BotonRojoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonRojoActionPerformed
        // TODO add your handling code here:
        this.BarraEstado.setText("Rojo");
        this.Lienzo.setColor(Color.red);
    }//GEN-LAST:event_BotonRojoActionPerformed

    private void BotonAzulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAzulActionPerformed
        // TODO add your handling code here:
         this.BarraEstado.setText("Azul");
            this.Lienzo.setColor(Color.blue);
    }//GEN-LAST:event_BotonAzulActionPerformed

    private void BotonBlancoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonBlancoActionPerformed
        // TODO add your handling code here:
          this.BarraEstado.setText("Blanco");
        this.Lienzo.setColor(Color.white);
    }//GEN-LAST:event_BotonBlancoActionPerformed

    private void BotonAmarilloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAmarilloActionPerformed
        // TODO add your handling code here:
        this.BarraEstado.setText("Amarillo");
        this.Lienzo.setColor(Color.yellow);
    }//GEN-LAST:event_BotonAmarilloActionPerformed

    private void BotonVerdeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonVerdeActionPerformed
        // TODO add your handling code here:
        this.BarraEstado.setText("Verde");
        this.Lienzo.setColor(Color.green);
    }//GEN-LAST:event_BotonVerdeActionPerformed

    private void CheckBoxRellenoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckBoxRellenoActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_CheckBoxRellenoActionPerformed

    private void CheckBoxRellenoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_CheckBoxRellenoItemStateChanged
        // TODO add your handling code here:
        this.Lienzo.setRelleno(this.CheckBoxRelleno.isSelected());
    }//GEN-LAST:event_CheckBoxRellenoItemStateChanged

    /*Cuando pulsamos el lapiz en la barra de estado ponemos lapiz, y mandamos la forma punto*/
    private void BotonLapizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonLapizActionPerformed
        // TODO add your handling code here:
        this.BarraEstado.setText("Lapiz");
        this.Lienzo.setForma("Punto");
        /*
        this.BotonLinea.setSelected(false);
        this.BotonRectangulo.setSelected(false);
        this.BotonOvalo.setSelected(false);
        */
     
    }//GEN-LAST:event_BotonLapizActionPerformed

    private void BotonLineaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonLineaActionPerformed
        // TODO add your handling code here:
          this.BarraEstado.setText("Linea");
          this.Lienzo.setForma("Linea");
         /*
        this.BotonLapiz.setSelected(false);
        this.BotonRectangulo.setSelected(false);
        this.BotonOvalo.setSelected(false);
        */
            
    }//GEN-LAST:event_BotonLineaActionPerformed

    private void BotonRectanguloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonRectanguloActionPerformed
        // TODO add your handling code here:
        this.BarraEstado.setText("Rectangulo");
        this.Lienzo.setForma("Rectangulo");
         /*
        this.BotonLapiz.setSelected(false);
        this.BotonLinea.setSelected(false);
        this.BotonOvalo.setSelected(false);
        */
        
        
    }//GEN-LAST:event_BotonRectanguloActionPerformed

    private void BotonOvaloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonOvaloActionPerformed
        // TODO add your handling code here:
        this.BarraEstado.setText("Ovalo");
        this.Lienzo.setForma("Ovalo");
         /*
        this.BotonLapiz.setSelected(false);
        this.BotonRectangulo.setSelected(false);
        this.BotonLinea.setSelected(false);
        */
        
    }//GEN-LAST:event_BotonOvaloActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup BarraColores;
    private javax.swing.JLabel BarraEstado;
    private javax.swing.JToolBar BarraHerramientas;
    private javax.swing.JMenuBar BarraMenu;
    private javax.swing.JPanel BarraPaleta;
    private javax.swing.JMenuItem BotonAbrir;
    private javax.swing.JToggleButton BotonAmarillo;
    private javax.swing.JMenu BotonArchivo;
    private javax.swing.JToggleButton BotonAzul;
    private javax.swing.JToggleButton BotonBlanco;
    private javax.swing.JMenu BotonEdicion;
    private javax.swing.JMenuItem BotonGuardar;
    private javax.swing.JToggleButton BotonLapiz;
    private javax.swing.JToggleButton BotonLinea;
    private javax.swing.JToggleButton BotonNegro;
    private javax.swing.JMenuItem BotonNuevo;
    private javax.swing.JToggleButton BotonOvalo;
    private javax.swing.JToggleButton BotonRectangulo;
    private javax.swing.JToggleButton BotonRojo;
    private javax.swing.JToggleButton BotonVerde;
    private javax.swing.ButtonGroup BotonesHerramientas;
    private javax.swing.JCheckBoxMenuItem CheckBoxBarraEstado;
    private javax.swing.JCheckBox CheckBoxRelleno;
    public practica4.Lienzo Lienzo;
    private javax.swing.JPanel PaletaColores;
    private javax.swing.JPanel VistaGrafica;
    // End of variables declaration//GEN-END:variables
}
